### ISSUE TITLE
Error when attempting to run bot

### ISSUE THREAD

**Issue by ShafferZee** [MysteryPancake/Discord-Reposter#2]
After I use the repost command I get this error.

LOADING LIBRARIES...
READY FOR ACTION!
/opt/discord_bots/discord-reposter/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:123
    if (options.embed && options.embed.file) {
                ^

TypeError: Cannot read property 'embed' of null
    at TextChannel.send (/opt/discord_bots/discord-reposter/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:123:17)
    at Client.<anonymous> (/opt/discord_bots/discord-reposter/bot.js:53:12)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (/opt/discord_bots/discord-reposter/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/opt/discord_bots/discord-reposter/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/opt/discord_bots/discord-reposter/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/opt/discord_bots/discord-reposter/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocketClient.internalOnMessage (/opt/discord_bots/discord-reposter/node_modules/uws/uws.js:103:17)
    at native.client.group.onMessage (/opt/discord_bots/discord-reposter/node_modules/uws/uws.js:57:15)

**Comment by MysteryPancake** [comment]
Sorry, this bot is a bit buggy. I'll try to fix this

**Comment by MysteryPancake** [comment]
Yep, I also need to change setGame to setActivity.

**Comment by ShafferZee** [comment]
Yup, this can be easily changed in line 11 of the bot.js and coolbot.js
Just swap out setGame for setActivity

**Comment by gbougadis** [comment]
Yeah that worked when I changed it to setActivity but now it just gets stuck on READY FOR ACTION! when I run it and nothing loads and I have the inability to type anything. Thanks for the help anyway fellas.

**Comment by MysteryPancake** [comment]
Does it go online on Discord? If so, it might work if you type /repost and then an ID in Discord

**Comment by gbougadis** [comment]
Figured it all out. Now I just have the same issue as Shaffer, I'll see if I can get it on my own. Good luck!

**Comment by ShafferZee** [comment]
@gbougadis 
I fixed this issue by updating npm. You can do this by running `sudo npm i -g npm`
The bot again reached the ready for action state and reposted content when running `/repost`.
However, I then ran into a different "timeout" error I'll post here later.

**Comment by gbougadis** [comment]
Yeah that fixed the error. It's weird though because when I type /repost <my server id> I always get the "couldn't repost to" error . I haven't come across a timeout error yet but that's probably because I cannot get it to repost.

**Comment by MysteryPancake** [comment]
Oh, okay. By the timeout error I think you mean the ECONRESET thing. That happens to me when it tries to fetch too many messages at once. I probably need to make it all synchronous to fix this.

Sorry about all these errors. You may want to use another bot that isn't such a mess

**Comment by MysteryPancake** [comment]
I updated the bot now. [I changed a bunch of stuff](https://github.com/MysteryPancake/Discord-Reposter/commit/66d62792471c7c8e33dca7ee63bb65294ceea9df). it's all synchronous now so there shouldn't be too many timeout errors. Please tell me if this fixes anything!

**Comment by MysteryPancake** [comment]
I just updated the bot and it now reposts forward instead of backward! I've made a lot of changes over the past few weeks, so please tell me if this fixes anything, or even if it causes more problems!

**Comment by MysteryPancake** [comment]
I think I will close this issue, because the bot is a lot better than it used to be, and I haven't had any timeout errors so far.
